version: "3.3"
services:  
  app-silvestrini:
    image: mrsilvestrini/app-silvestrini:v1.0.0
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "1"
          memory: "50M"
      restart_policy:
        condition: on-failure
    
    volumes:      
      - volume-app-silvestrini:/usr/share/nginx/html
    networks:
      - skynet
    ports:
      - 8080:80

volumes:
  volume-app-silvestrini:

networks:
  skynet:
    