version: "3.3"
services:  
  app-silvestrini:
    image: mrsilvestrini/app-silvestrini:v1.0.0
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "1"
          memory: "50M"
      restart_policy:
        condition: on-failure
    
    volumes:      
      - volume-app-silvestrini:/usr/share/nginx/html
    networks:
      - skynet
    ports:
      - 8080:80
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  volume-app-silvestrini:

networks:
  skynet:
    