version: "3.3"

services:
  web:
    image: nginx
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"
    networks:
      - skynet

networks:
  skynet:

      



