version: "3.3"

services:
  web:
    image: nginx
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"
    networks:
      - skynet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  skynet:

      



